// Cloudflare Pages Function: HTTPS proxy for plain-HTTP radio streams.
//
// Browsers block http:// audio on an https:// page (mixed content), so the
// app requests /listen?... instead and this function pipes the stream through.
//
//   /listen?id=<stationId>   -> follows Radio Garden's listen redirect server-side
//   /listen?url=<streamUrl>  -> proxies a direct stream URL from the snapshot
//
// To avoid being an open proxy, ?url= targets must be on a host that appears
// in the crawled snapshot (data/stream-hosts.json, generated by tools/snapshot.mjs).

import STREAM_HOSTS from '../data/stream-hosts.json';

const API_BASE = 'https://radio.garden/api';
// Radio Garden challenges non-browser user agents
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36';

const hostSet = new Set(STREAM_HOSTS);

export async function onRequestGet({ request }) {
  const params = new URL(request.url).searchParams;
  const id = params.get('id');
  const url = params.get('url');

  let target;
  if (id) {
    if (!/^[\w-]{4,32}$/.test(id)) {
      return new Response('Invalid station id', { status: 400 });
    }
    target = `${API_BASE}/ara/content/listen/${id}/channel.mp3`;
  } else if (url) {
    let u;
    try {
      u = new URL(url);
    } catch {
      return new Response('Invalid url', { status: 400 });
    }
    if ((u.protocol !== 'http:' && u.protocol !== 'https:') || !hostSet.has(u.host)) {
      return new Response('Host not allowed', { status: 403 });
    }
    target = u.toString();
  } else {
    return new Response('Missing id or url parameter', { status: 400 });
  }

  let upstream;
  try {
    upstream = await fetch(target, {
      headers: { 'User-Agent': UA, 'Icy-MetaData': '0' },
      redirect: 'follow',
    });
  } catch {
    return new Response('Upstream fetch failed', { status: 502 });
  }

  if (!upstream.ok) {
    return new Response(`Upstream error ${upstream.status}`, { status: 502 });
  }

  // Pass the audio through, keeping only the headers that matter
  const headers = new Headers();
  headers.set('Content-Type', upstream.headers.get('Content-Type') || 'audio/mpeg');
  headers.set('Cache-Control', 'no-store');
  return new Response(upstream.body, { status: 200, headers });
}
